### PR TITLE
Add "raed" for Pan-Hispanic Dictionary of Doubts

### PR DESCRIPTION
**Pull request by neubarth**

### CODE REVIEW

**Comment by georgjaehnig** [comment]
Thanks! Doesn't it better fit into `es` namespace?

**Comment by neubarth** [comment]
> Thanks! Doesn't it better fit into `es` namespace?

Hm, I'm not sure. In general, I think that **monolingual** dictionaries should be added to the global namespace:

1. Users could then use the keyword directly, without preprending the namespace, e.g. `raed` instead of `es.raed`.
2. The search itself does not depend on the user's language, i.e. there will never be entries for `en.raed`, `nl.raed` etc. This would only be the case if we add a general `dict` keyword, and add entries for each country's namespace:
  - `.es.dict` -> lookup in RAE dictionary
  - `.de.dict` -> lookup in Duden dictionary
  - `.gb.dict` -> lookup in Cambridge dictionary
  - `.us.dict` -> lookup in Merriam Webster
  - etc.

**Comment by georgjaehnig** [comment]
(First, I thought about `es` (Spanish language namespace), not `.es` (Spain namespace))

> Users could then use the keyword directly, without preprending the namespace, e.g. raed instead of es.raed.

Not necessarily. One could add `es` to their namespace setting, also with lower priority. E.g. a setting

- o
- es
- de
- .de

would still allow you to use German language shortcuts, but also enable `raed`, in case it's not overwritten by `de` or `.de`.

 >  i.e. there will never be entries for en.raed, nl.raed etc

Not necessarily. There could some completely other service where the same shortcut would be convenient. Yes, not likely, but think about shorter shortcuts, like `db`. We've already put that into `.de`, although there is no `o.db`. 

That way, we have the same policy for shorter and longer shortcuts: If possible, we put them into a namespace.

Sounds convincing? Feel free to object. :)

**Comment by neubarth** [comment]
> Sounds convincing? Feel free to object. :)

Well, I guess there are pros and cons ;-)
I updated the PR.

**Pull request merged**
